# automations/energyua_outage_tomorrow.yaml
# Вставляти через UI: Settings → Automations → Add → Edit in YAML
alias: 'Енергія: з’явився графік на завтра'
mode: single
trigger:
  - platform: state
    entity_id: sensor.energyua_22_tomorrow_fresh
    to: 'True'
action:
  - service: notify.mobile_app_YOUR_APP
    data:
      title: '⚡ Оприлюднено графік на завтра'
      message: "{{ states('sensor.energyua_22_tomorrow_brief') }}"
  - service: persistent_notification.create
    data:
      title: '⚡ Графік відключень на завтра'
      message: "{{ states('sensor.energyua_22_tomorrow_brief') }}"
